
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  # stubDomains: |
  #   {"tera-mkpl.fr": ["10.96.0.10"]}
  upstreamNameservers: |
    ["8.8.8.8", "8.8.4.4"]
