
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: algofab
spec:
  selector:
    app: ldap
  ports:
    - targetPort: 80
      port: 80
      name: http
    - targetPort: 389
      port: 389
      name: ldap


---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: algofab
spec:
  selector:
    app: mongo
  ports:
    - targetPort: 27017
      port: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: im
  namespace: algofab
spec:
  selector:
    app: im
  ports:
    - targetPort: 32080
      port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rh
  namespace: algofab
spec:
  selector:
    app: rh
  ports:
    - targetPort: 3000
      port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: algofab
spec:
  selector:
    app: portal
  ports:
    - targetPort: 8080
      port: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: algofab
spec:
  selector:
    app: proxy
  ports:
    - targetPort: 80
      port: 80

--- 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-access
  namespace: algofab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/send-timeout: "3600"
    nginx.org/websocket-services: "portal"
spec:
  rules:
  - host: ws67-af-portal.tl.teralab-datascience.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: portal
          servicePort: 80

  - host: ws67-af-ldap.tl.teralab-datascience.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: ldap
          servicePort: 80

  - host: ws67-af-rh.tl.teralab-datascience.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: rh
          servicePort: 80

  - host: ws67-af-proxy.tl.teralab-datascience.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: proxy
          servicePort: 80
