
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc
  namespace: algofab
provisioner: memorialhealth/nfs 

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: algofab
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-sc
  nfs:
    path: /home/skante/kube_algofab
    server: 10.32.2.2

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc0001
  namespace: algofab
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc
  volumeName: "pv0001"

# ---


# apiVersion: v1
# kind: Pod
# metadata:
#   name: busybox
# spec:
#   securityContext:
#     runAsUser: 1002
#     runAsGroup: 1002
#   containers:
#   - image: ubuntu
#     imagePullPolicy: IfNotPresent
#     name: busybox
#     command: ["/bin/sh"]
#     args: ["-c", "while true; do echo hello; sleep 10;done"]
#     volumeMounts:
#     - mountPath: /data
#       name: my-data
#       subPath: data/ldap
#   volumes:
#   - name: my-data
#     persistentVolumeClaim:
#       claimName: pvc0001