
version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - db:/data/db
  api:
    #image: node
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/root/server
    depends_on:
      - mongo

volumes:
  db: