
version: '3'

services:
  ldap:
    image: algofab2018/ldap
    #build: ./services/ldap
    volumes:
      - ./services/ldap/conf/entrypoint.sh:/tmp/entrypoint.sh
      - ./data/ldap/:/data
    ports:
      - ${LDAP_COMPOSE_PORT}:80
    env_file:
      - .env
    privileged: true

  mongo:
    image: mongo
    volumes:
      - ./data/mongo/:/data/db

  api:
    image: algofab2018/marketplace
    #build: ./services/algofab
    command: API
    ports:
      - ${API_COMPOSE_PORT}:3000
    env_file:
      - .env
    user: root
    volumes:
      - ./services/algofab:/home/admin/algofab
    depends_on: 
      - mongo
      
  portal:
    image: algofab2018/marketplace
    #build: ./services/algofab
    command: Portal
    ports:
      - ${PORTAL_COMPOSE_PORT}:8080
    env_file:
      - .env
    user: root
    volumes:
      - ./services/algofab:/home/admin/algofab
      - ./data/accounts/:/accounts
    depends_on: 
      - mongo

  im:
    image: algofab2018/marketplace
    #build: ./services/algofab
    command: IM-Server
    env_file:
      - .env
    volumes:
      - ./services/algofab:/home/admin/algofab
      - ./data/accounts/:/accounts
    depends_on: 
      - mongo

  # rh:
  #   image: algofab2018/marketplace
  #   #build: ./services/algofab
  #   command: RH-Server
  #   ports:
  #     - 8083:3000
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./services/algofab:/home/admin/algofab
  #   depends_on: 
  #     - mongo


