
version: '3'

services:
  ldap:
    image: algofab2018/ldap
    build: ./services/ldap
    # entrypoint: /bin/sh -c 'while [ true ]; do echo "turn"; sleep 10; done'
    volumes:
      - ./services/ldap/conf/entrypoint.sh:/tmp/entrypoint.sh
      - ./data/ldap/:/data
    ports:
      - 8081:80
    env_file:
      - .env
    privileged: true

  mongo:
    image: mongo
    volumes:
      - ./data/mongo/:/data/db

  api:
    image: algofab2018/marketplace
    build: ./services/algofab
    command: API
    ports:
      - 8084:3000
    env_file:
      - .env
    user: root
    volumes:
      - ./services/algofab:/home/admin/algofab
    depends_on: 
      - mongo
      
  portal:
    image: algofab2018/marketplace
    build: ./services/algofab
    command: Portal
    ports:
      - 8082:8080
    env_file:
      - .env
    user: root
    volumes:
      - ./services/algofab:/home/admin/algofab
      - ./data/accounts/:/accounts
    depends_on: 
      - mongo

  im:
    image: algofab2018/marketplace
    build: ./services/algofab
    command: IM-Server
    env_file:
      - .env
    volumes:
      - ./services/algofab:/home/admin/algofab
      - ./data/accounts/:/accounts
    depends_on: 
      - mongo

  # rh:
  #   image: algofab2018/marketplace
  #   build: ./services/algofab
  #   command: RH-Server
  #   ports:
  #     - 8083:3000
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./services/algofab:/home/admin/algofab
  #   depends_on: 
  #     - mongo


  # portal:
  #   build: ./algofab
  # im:
  #   build: ./algofab
  # rh:
  #   build: ./algofab
