apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
  namespace: algofab
data:
  LDAP_SERVER_NAME: "Algofab LDAP"
  LDAP_BASE_DN: "dc=ldap,dc=algofab,dc=fr"
  LDAP_DEBCONF_DOMAIN: "ldap.algofab.fr"
  LDAP_DEBCONF_ORG: "TeraLab IMT"
  LDAP_PASSWORD: "password"
  
  PORTAL_EXT_PROTOCOL: "https"
  PORTAL_EXT_NAME: "ws67-af-portal.tl.teralab-datascience.fr"
  
  PROXY_EXT_PROTOCOL: "https"
  PROXY_EXT_NAME: "ws67-af-proxy.tl.teralab-datascience.fr"
  
  DOCS_EXT_PROTOCOL: "https"
  DOCS_EXT_NAME: "ws67-af-docs.tl.teralab-datascience.fr"
  
--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: common
  namespace: algofab
data:
  PV_DIR: /home/skante/Kube_algofab
  PV_HOST: 10.200.209.30
  
